pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "petru1405/devops-public:${env.BUILD_NUMBER}"
    }
    stages {
        stage('Build') {
            steps {
                bat "\"%MAVEN_HOME%\\mvnw.cmd" package"
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_IMAGE}", "dockerhello/")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        bat "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                        dockerImage.push()
                        bat "docker logout"
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
